hw1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to:"home#index"
  resources :cars do   #cars made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :makes do   #makes made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :parts do   #parts made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hw1/app/models/car.rb
class Car < ApplicationRecord
  belongs_to :make                      
  has_and_belongs_to_many :parts 
                                  
  validates_associated :parts           #Validates :parts at the same time
  validates :make, presence: true       #Checks presence of a make 
  validates :parts, presence: true      #Checks presence of parts 
  validates :model, length: {minimum: 2}      #Checks presence of model
  validates :vin, uniqueness: true, length: {minimum: 11, maximum: 17}, format: {with: /\A[0-9A-Z]*\z/, message: "only accepts upper-case letters and numbers"}
                                        #Checks uniquness and length req's for a VIN, also numerals and capitalized letters only
                                        #SOURCE: Slides 14-17 from 07DebugValidationCSS
                                        #SOURCE for regular expression help: https://stackoverflow.com/questions/24422018/rails-validates-with-regex-is-not-working

  
end                                     

hw1/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    @parts = Part.all
  end

  # GET /cars/1/edit
  def edit
    @parts = Part.all    
  end

   #SEARCH    To search vins & models from cars in the database, source: Slide 31 from 06RoutesSearch Slideset
  def search 
  
    @cars = Car.where("vin like :search OR model like :search", search: "%#{params[:query]}%")
    render :index
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make_id, :model, :vin, :part_ids=>[])
                                              #Most of this line was auto-generated, however
                                              #', :part_ids=>[]' is added to force a Car object
                                              #to also need Part(s).
                                              #Citation: Guided by 03ActiveRecord PPP slide 33
    end
end

hw1/app/helpers/cars_helper.rb
module CarsHelper
end

hw1/app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make_id %>
    <!-- <%= form.text_field :make_id %> -->
    <%= form.collection_select(:make_id, Make.all, :id, :name) %>
    <!-- Could not figure out how to get textfields to lookup the make by name rather than ID,
    so instead I made a dropdown menu, with help from:
    https://stackoverflow.com/questions/8907867/can-someone-explain-collection-select-to-me-in-clear-simple-terms -->
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <!--The following <div block was added to allow parts to be selected as a checklist, 
  allowing for multiple selections.  Citation:  From PPP 03ActiveRecord, slide 38 and
  https://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_check_boxes -->
  <div class="field">
    <%= form.label :part_id %>
    <%= form.collection_check_boxes(:part_ids, Part.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hw1/app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

hw1/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>
<img src="https://aparm.000webhostapp.com/C&PCimages/cars_title.png">
<div class="jumbotron bg-dark move-up">
<div class="float-left">
<%= link_to 'New Car', new_car_path %>
</div>
<div class="float-right">
<%= form_tag(search_cars_url, method: "get") do %>   <!-- Add search for to html for VIN and model of car -->
  <%= label_tag(:query, "") %>
  <%= text_field_tag(:query, nil, placeholder: "Search by VIN or model") %>
  
  <%= submit_tag("Search") %>
<% end %>
</div>
<br><br>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Vin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make.name if car.make %></td>   <!-- Displays the name of the Make, rather than the id; added "if car.make" to not allow nil values -->
        <td><%= car.model %></td>
        <td><%= car.vin %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

hw1/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

hw1/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make.name %>   <!--.name was added to display the name of the make on Car creation-->
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<!-- Part does not currently exist in the car form, as the relationship was
added after the auto-generated code of the scaffolds, so the following block was
added to have the Part objects load from the parts table.
Citation: From PPP 03ActiveRecord, slide 39-->
<p>
  <strong>Parts:</strong>
</p>
  <ul>
      <% @car.parts.each do |part| %>
        <li><%= part.name %></li>
      <% end %>
  </ul>

  

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>