hw1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to:"home#index"
  resources :cars do   #cars made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :makes do   #makes made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :parts do   #parts made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hw1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cars & Parts Consortium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="content">
  
  <header>
  <div id="navBar">
  <!-- Fixed navbar adapted from https://getbootstrap.com/docs/4.3/examples/sticky-footer-navbar/# -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item">
         <%= link_to image_tag("https://aparm.000webhostapp.com/C&PCimages/navbar_logo.png"), home_index_path, class:"nav-link"%>
        </li> -->
        <li class="nav-item">
          <%= link_to 'Cars', cars_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Makes', makes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Parts', parts_path, class: "nav-link" %>
        </li>
        </ul>
        <ul class="nav navbar-nav navbar-center">
        <%= link_to image_tag("https://aparm.000webhostapp.com/C&PCimages/navbar_logo.png"), home_index_path, class:"nav-link"%>

        </ul>

      <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to_if(user_signed_in?, 'Log out', destroy_user_session_path, method: :delete, class: "nav-link"){link_to 'Log in', new_user_session_path, class: "nav-link"} %>
        </li>
      </ul>
    </div>
  </nav>
  </div>
</header>
<div class="pad-top"></div>
<br>
    <%= yield %>
    <div class="pad-top"></div>
    <footer class="footer mt-auto py-3 fixed-bottom bg-dark">
    <div class="container">
    <span class="text-muted">CS3710: Web App Development student application created by Alex Parmentier</span>
  </div>
  </footer>
</body>
</html>