hw1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to:"home#index"
  resources :cars do   #cars made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :makes do   #makes made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  resources :parts do   #parts made into a searchable collection,
    collection do       #citation: Slide 30 from 06RoutesSearch
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hw1/app/models/part.rb
class Part < ApplicationRecord
    has_and_belongs_to_many :cars
    validates :name, uniqueness: true, length: {minimum: 2}     #Added validations to check part name uniquness and the minimum length of 2 character
end

hw1/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  #SEARCH    To search parts in the database, source: Slide 31 from 06RoutesSearch Slideset
  def search 
      @parts = Part.where("name like ?", "%#{params[:query]}%")
      render :index
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:name)
    end
end

hw1/app/helpers/parts_helper.rb
module PartsHelper
end

hw1/app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hw1/app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

hw1/app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>
<img src="https://aparm.000webhostapp.com/C&PCimages/parts_title.png">
<div class="jumbotron bg-dark move-up">
<div class="float-left">
<%= link_to 'New Part', new_part_path %>
</div>
<div class="float-right">
<%= form_tag(search_parts_url, method: "get") do %>   <!-- Add search for parts -->
    <%= label_tag(:query, "") %>
    <%= text_field_tag(:query, nil, placeholder: "Search by name") %>
    <%= submit_tag("Search") %>
<% end %>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

hw1/app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

hw1/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>